//Priorities
HIGHEST_PROMOTABLE_PRIORITY = 100;
COLONY_MANAGEMENT_PRIORITY = 90;
COLONY_NECESSARY_ENERGY_PRIORITY = 87;
COLONY_DEFENSE_PRIORITY = 85;
COLONY_SCOUTING_PRIORITY = 82;
NECESSARY_CREEPS_PRIORITY = 70;
ROOM_UPGRADE_CREEPS_PRIORITY = 65;
COLONY_EXTRA_ENERGY_PRIORITY = 60;
COLONY_NONESSENTIAL_PRIORITY = 50;
DEFAULT_PRIORITY = 10;


// Colony configuration
COLONY_MAX_RANGE = 2;
COLONY_MAX_ROOMS_TO_TRAVEL = 2;
COLONY_INFO_UPDATE_FREQUENCY = 200; //Update every N ticks
COLONY_ROAD_HITS_CRITICAL_THRESHOLD = 0.2;